### PR TITLE
feat: migrate to Nuxt 4

### PR DESCRIPTION
**Pull request by mubaidr**
### What is accomplished by your PR?

Adjusting this template to support Nuxt 4:
- add compatibility version 4 to `nuxt.config`
- migrate to new directory structure
- `compatibilityDate` in `nuxt.config`
- [Shared Prerender Data](https://nuxt.com/docs/getting-started/upgrade#shared-prerender-data) is enabled by default in Nuxt 4, so set `key`s for `useAsyncData`

### Is there something controversial in your PR?

nope

### Link to the Issue

[Upgrade to Nuxt 4](https://github.com/vuesion/vuesion/issues/637)

# Checklist

### New Feature / Bug Fix

- [x] Run unit tests to ensure all existing tests are still passing
- [x] Add new passing unit tests to cover the code introduced by your PR
- [x] Add Story for a new component introduced by your PR

### CODE REVIEW

**Comment by mubaidr** [comment]
I don't think there is any breaking change. Everything works as it is. 

Change list huge because of the directory move and then path adjustment for moved files. 

Btw I have run dev mode it's working fine, plus:
- lint
- build
- test

Modes passed too. But looking at the CI results, it seems that I have missed the storybook results. Apologies, I will look into this later today.

**Comment by mubaidr** [comment]
Storybook has been fixed too. Both `dev` and `build` work fine for storybook now. 

TODO: I need to check and update documentation to reflect directories and updated config references.

**Comment by devCrossNet** [comment]
@mubaidr do you know if anything changed regarding environment variables? It seems the CI fails because of the missing `NUXT_AUTH_SECRET` variable. Here is the error description of the auth module: https://auth.sidebase.io/resources/error-reference#auth-no-secret

**Comment by mubaidr** [comment]
> @mubaidr do you know if anything changed regarding environment variables? It seems the CI fails because of the missing `NUXT_AUTH_SECRET` variable. Here is the error description of the auth module: https://auth.sidebase.io/resources/error-reference#auth-no-secret


I will look into ci results.

**Comment by mubaidr** [comment]
This is strange, maybe you can point me in right direction, but on local environment all test/ build status is ok. 

Screenshot_20241205_010443

**Comment by devCrossNet** [comment]
@mubaidr the CI says that NUXT_AUTH_SECRET isn't set. I don't know why, but maybe we can have a quick fix to test the rest of the workflow. in the file: `src/server/api/auth/[...].ts` in line 22, you could add something like this: `secret: process.env.NUXT_AUTH_SECRET || 'my-secret',`. We can investigate later if it's an issue with the nuxt 4 update or github.

**Comment by mubaidr** [comment]
Sure, I will try this. 

But the nitro server has too, which is the main issue I believe. But nevertheless I will try adding auth secret.

**Comment by mubaidr** [comment]
Paths in templates updated too. Ready for review.

**Review by devCrossNet — APPROVED** [review]
LGTM 🥳 

Thank you very much for this great contribution ❤️

**Comment by mubaidr** [comment]
@devCrossNet Thanks, are we also looking for `vusion/docs` update, related to this?

**Comment by devCrossNet** [comment]
@mubaidr we can do that right after we merge it into the main branch 👍

**Comment by mubaidr** [comment]
> @mubaidr we can do that right after we merge it into the main branch 👍


I agree, we will also have conclusion for this discussion, which is dependency of the docs: https://github.com/vuesion/vuesion/issues/637

**Pull request merged**
