### PR TITLE
build: add cross-env

### PR DESCRIPTION
**Pull request by Loopios7**
change package.json to use cross-env to set variables

allows for running launch scripts using environment variables on windows and linux
closes [github issue 571](https://github.com/vuesion/vuesion/issues/571)

### CODE REVIEW

**Comment by devCrossNet** [comment]
Thank you for contributing! Can you add cross-env as a dependency to the package.json? otherwise, I think it won't work for people that don't have it installed globally.

**Comment by Loopios7** [comment]
> Thank you for contributing! Can you add cross-env as a dependency to the package.json? otherwise, I think it won't work for people that don't have it installed globally.

It's already in the package.json dependencies

**Comment by devCrossNet** [comment]
Ok, sorry I missed that one. Now I see it 👍

**Review by devCrossNet — APPROVED** [review]
LGTM 👍

**Pull request merged**
