### PR TITLE
Windows tier

### PR DESCRIPTION
**Pull request by HeavenlyEntity**
### What is accomplished by your PR?

I have added a FAQ page for users in case when issues expire they can visit there to find a solution. 

### Is there something controversial in your PR?

Please provide feedback for me if there is something that should be added or revised to make more appealing.

### Link to the Issue

N/A

### CODE REVIEW

**Comment by HeavenlyEntity** [comment]
I was getting issues committing this too I had to uncheck `use GitHub hooks` for it to successfully commit and push. I also already updated the master FAQ.md page where you can see the added troubleshooting steps for the 500 error code issue.

**Comment by devCrossNet** [comment]
@HeavenlyEntity that's because of the commit message linting. There is a section in the contribution guidelines about it. It has to follow a specific format.

Please let's use PR's to track changes in all the other repositories, too.

**Comment by devCrossNet** [comment]
@HeavenlyEntity and always create PR's based on the `next` branch, that's also in the contribution guidelines.

**Comment by HeavenlyEntity** [comment]
> @HeavenlyEntity and always create PR's based on the `next` branch, that's also in the contribution guidelines.

Okay thanks for letting me know.

**Pull request merged**
